filetags/urls.py
from django.conf.urls import patterns, url
from views import index, add_file, search_tag, search_files, show_file, delete_file, edit_file

js_info_dict = {
    'packages': ('filetags', ),
}

urlpatterns = patterns('',
    url(r'^$', index, name='filetags-index'),
    url(r'^add-file/$', add_file, name='filetags-add-file'),
    url(r'^search-tag/$', search_tag, name='filetags-search-tag'),
    url(r'^search-files/$', search_files, name='filetags-search-files'),
    url('^file/(?P<id>\d+)/$', show_file, name='filetags-show-file'),
    url('^delete-file/(?P<id>\d+)/$', delete_file, name='filetags-delete-file'),
    url('^edit-file/(?P<id>\d+)/$', edit_file, name='filetags-edit-file'),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
)

filetags/models.py
# coding=utf-8
from unidecode import unidecode
from sorl.thumbnail import get_thumbnail, delete
from django.db import models
from django.utils.translation import ugettext as _
from django.core.validators import MinLengthValidator
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_delete, pre_delete
from django.dispatch import receiver
from filetags.settings import IMAGE_SIZES
from filetags.utils import OverwritingFileSystemStorage, get_file_path

fs = OverwritingFileSystemStorage()


class Tags(models.Model):
    name = models.CharField(_(u'Name (required)'), max_length=50, unique=True,
                            blank=False, null=False,
                            validators=[MinLengthValidator(3)])
    slug = models.CharField('Slug', max_length=50, blank=False, null=False)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')
        ordering = ('name', 'slug')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super(Tags, self).save(*args, **kwargs)


class MimeTypes(models.Model):
    name = models.CharField(_(u'MimeType (required)'), max_length=200,
                            unique=True, blank=False, null=False)

    class Meta:
        verbose_name = _('MimeType')
        verbose_name_plural = _('MimeTypes')
        ordering = ('name', )


class Files(models.Model):
    file = models.FileField(_('File (required)'), storage=fs,
                            upload_to=get_file_path, max_length=255,
                            blank=False, null=False)
    added = models.DateTimeField(_('Added'), auto_now_add=True, editable=False,
                                 blank=False, null=False)
    edited = models.DateTimeField(_('Edited'), auto_now=True, blank=False,
                                  null=False)
    title = models.CharField(_(u'Title (required)'), max_length=80,
                             blank=False, null=False,
                             validators=[MinLengthValidator(7)])
    comment = models.TextField(_(u'Comment'), blank=True, null=True)
    tags = models.ManyToManyField(Tags, verbose_name=_(u'Tags (required)'),
                                  blank=False, null=False)
    mimetype = models.ForeignKey(MimeTypes, blank=False, null=False)
    user = models.ForeignKey(User, blank=False, null=False)

    def thumb(self):
        """
        Return dependent on mimetype the smallest thumbnail url or file name.
        """
        if self.mimetype.name.split('/')[0] == 'image':
            thumb = get_thumbnail(self.file, IMAGE_SIZES[-1])
            return thumb.url
        else:
            return str(file.name)

    def thumbs_delete(self):
        """
        Delete all thumbnails assigned to this object.
        """
        if self.mimetype.name.split('/')[0] == 'image':
            delete(self.file, delete_file=False)

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')
        ordering = ('added', )
        permissions = (
            ("view_files", "Can see available files"),
        )

    @models.permalink
    def get_absolute_url(self):
        return ('filetags-show-file', (), {'id': self.id})


@receiver(pre_delete, sender=Files)
def delete_tags(sender, **kwargs):
    """
    Delete tags assigned to object before delete.!!!!!!!!!!!!!!!!!!!!!1
    """
    f = kwargs.get('instance')
    for tag in f.tags.all():
        if tag.files_set.count() == 1:
            tag.delete()


@receiver(post_delete, sender=Files)
def delete_files(sender, **kwargs):
    f = kwargs.get('instance')
    if Files.objects.filter(mimetype=f.mimetype).count() == 0:
        try:
            mimetype = MimeTypes.objects.get(pk=f.mimetype.pk)
        except MimeTypes.DoesNotExist:
            mimetype = None
        else:
            mimetype.delete()
    if f.file:
        if f.mimetype.name.split('/')[0] == 'image':
            delete(f.file)
        else:
            f.file.delete(save=False)

filetags/templates/filetags/add.html
{% extends "filetags/base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block extra_js %}
    <script type="text/javascript" src="{% url django.views.i18n.javascript_catalog %}"></script>
    <script src="{{ STATIC_URL }}filetags/js/csrf.js"></script>
    <script src="{{ STATIC_URL }}filetags/js/jquery.autocomplete.min.js"></script>
    <script>var SEARCH_TAG = "{% url filetags-search-tag %}"</script>
    <script src="{{ STATIC_URL }}filetags/js/search_tag.js"></script>
    <script src="{{ STATIC_URL }}filetags/js/jquery.validate.js"></script>
    <script src="{{ STATIC_URL }}filetags/js/validate.js"></script>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}filetags/css/jquery.autocomplete.css" />
{% endblock %}

{% block title %}{% if form.instance.id %}{% trans 'Edit file' %}{% else %}{% trans 'Add new file' %}{% endif %}{% endblock %}

{% block content %}
    <div class="span12">
	    {% if form.non_field_errors %}
	        <div class="alert alert-error">
	            <a class="close" data-dismiss="alert">×</a>
	            <h4 class="alert-heading">{% trans "Error" %}!</h4>
	            {% for error in form.non_field_errors %}{{ error }}{% endfor %}
	        </div>
	    {% endif %}
	    <form method="post" enctype="multipart/form-data" class="form-horizontal well"{% if query_string %} action="{{ query_string }}"{% endif %}>
	        <fieldset>
	            <legend>{% trans "Add new file" %}</legend>
	            {% csrf_token %}
	            {% for f in form %}
	                <div class="control-group {% if f.errors %}error{% endif %}">
	                    <label for="id_{{ f.html_name }}" class="control-label">{{ f.label }}</label>
	                    <div class="controls">
	                        {{ f|add_class:"span8" }}
	                        {% if f.errors %}<p class="help-block">{% for error in f.errors %}{{ error }}{% endfor %}</p>{% endif %}
	                    </div>
	                </div>
	            {% endfor %}
	            <div class="form-actions">
	                <input class="btn btn-primary" type="submit" value="{% if form.instance.id %}{% trans 'Edit' %}{% else %}{% trans 'Add' %}{% endif %}" />
	            </div>
	        </fieldset>
	    </form>
	</div>
{% endblock %}

filetags/templates/filetags/base.html
{% load i18n %}
{% load compress %}

<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8" />
        <title>FileTags - {% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="FileTags - file manager" />
        <meta name="author" content="Przemysław 'eshlox' Kołodziejczyk" />
        <link rel="stylesheet" href="{{ STATIC_URL }}filetags/css/bootstrap.min.css" />
        <style type="text/css">body{padding-top:20px;}</style>
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="span12">
					<div class="navbar">
					   <div class="navbar-inner">
					       <div class="container">
					           {% if file %}
					               <ul class="nav">
					                   <li><a href="javascript: history.go(-1)"><i class="icon-backward icon-white"></i> {% trans 'Back' %}</a></li>
					               </ul>
					           {% endif %}
					           <ul class="nav pull-right">
					               {% if perms.filetags.add_files %}
					                   <li><a href="{% url filetags-add-file %}{{ query_string }}"><i class="icon-plus icon-white"></i> {% trans 'Add file' %}</a></li>
					                   <li class="divider-vertical"></li>
					               {% endif %}
					               <li><a href="{% url filetags-index %}{{ query_string }}"><i class="icon-search icon-white"></i> {% trans 'Search files' %}</a></li>
					           </ul>
					       </div>
					   </div>
					</div>
                </div>
                {% block content %}{% endblock %}
            </div>
        </div>
        <script src="{{ STATIC_URL }}filetags/js/jquery.js"></script>
        {% block extra_js %}{% endblock %}
    </body>
</html>

filetags/templates/filetags/delete.html
{% extends "filetags/base.html" %}
{% load i18n %}
{% load isimage %}

{% block title %}{% trans 'Delete file' %}{% endblock %}

{% block content %}
    <div class="span12">
        {% if file %}
            <div class="thumbnail">
                <div class="caption">
                    <h5>{% trans 'Alert' %}</h5>
                    <p>{% trans 'Are you sure you want to delete this file?' %}</p>
                    {% if file.mimetype.name|isimage %}
                        <img src="{{ file.thumb }}" alt="{{ file.title }}" />
                    {% else %}
                        <a href="{{ file.file.url }}" title="{{ file.title }}">{{ file.title }}</a>
                    {% endif %}
                    <p>
		    <form action="{% url filetags-delete-file file.id %}{{ query_string }}" method="post">
			    {% csrf_token %}
                            <input class="btn btn-danger" type="submit" value="{% trans 'Yes' %}" />
                            <a class="btn" href="{% url filetags-show-file file.id %}{{ query_string }}">{% trans 'No' %}</a>
                        </form>
                    </p>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                <h4 class="alert-heading">{% trans 'Error' %}</h4>
                {% trans "File doesn't exists."  %}
            </div>
        {% endif %}
    </div>
{% endblock %}

filetags/templates/filetags/file.html
{% extends "filetags/base.html" %}
{% load i18n %}
{% load isimage %}
{% load size %}
{% load tags %}
{% load thumbnail %}

{% block title %}{% trans 'Show file' %}{% endblock %}

{% block extra_js %}
    <script src="{{ STATIC_URL }}filetags/js/jquery.zclip.min.js"></script>
    <script src="{{ STATIC_URL }}filetags/js/file.js"></script>
    <script type="text/javascript">var STATIC_URL = "{{ STATIC_URL }}"</script>
{% endblock %}

{% block extra_css %}
    <style type="text/css">p.center{text-align:center;}</style>
{% endblock %}

{% block content %}
    <div class="span12">
        {% if file %}
	        <div class="well">
		        {% if file.mimetype.name|isimage %}
		            <table class="table table-bordered">
		                <tr><th>{% trans 'Title' %}</th><td>{{ file.title }}</td></tr>
		                <tr><th>{% trans 'Comment '%}</th><td>{{ file.comment }}</td></tr>
		                <tr><th>{% trans 'Tags' %}</th><td>{{ file.tags|tags }}</td></tr>
		                <tr><th>{% trans 'Type' %}</th><td>{{ file.mimetype.name }}</td></tr>
		                {% if perms.filetags.change_files or perms.filetags.delete_files %}
		                    <tr>
		                        <th>{% trans 'Actions' %}</th>
		                        <td>
		                            {% if perms.filetags.change_files %}<a class="btn btn-primary" href="{% url filetags-edit-file file.id %}{{ query_string }}">{% trans 'Edit' %}</a>{% endif %}
		                            {% if perms.filetags.delete_files %}<a class="btn btn-danger" href="{% url filetags-delete-file file.id %}{{ query_string }}">{% trans 'Delete' %}</a>{% endif %}
		                        </td>
		                    </tr>
		                {% endif %}
		            </table>
		            <ul class="thumbnails">
		                <li>
		                    <div class="thumbnail">
		                        <img src="{{ MEDIA_URL }}{{ file.file }}" alt="{{ file.comment }}" />
		                        <p class="center">{% trans 'Size:' %} {{ file.file.size|filesizeformat }}, {% trans 'Dimensions:' %} {{ file.file.path|size }}px</p>
		                        <p class="center"><a class="btn download" href="{{ MEDIA_URL }}{{ file.file }}">{% trans 'Download' %}</a> <a class="btn copy" href="{{ MEDIA_URL }}{{ file.file }}">{% trans 'Copy link' %}</a>{% if query_string %} <a class="btn" href="#" onclick="OpenFile(ProtectPath('{{ MEDIA_URL }}{{ file.file }}'));return false;">{% trans 'Select' %}</a>{% endif %}</p>
		                    </div>
		                </li>
		            </ul>
		            {% for size in image_sizes|check_size:file.file %}
		                {% thumbnail file.file size as im %}
		                    <ul class="thumbnails">
		                        <li>
		                            <div class="thumbnail">
		                                <img src="{{ im.url }}" alt="{{ file.comment }}" /></p>
		                                <p class="center"><a class="btn download" href="{{ im.url }}">{% trans 'Download' %}</a> <a class="btn copy" href="{{ im.url }}">{% trans 'Copy link' %}</a>{% if query_string %} <a class="btn" href="#" onclick="OpenFile(ProtectPath('{{ im.url }}'));return false;">{% trans 'Select' %}</a>{% endif %}</p>
		                            </div>
		                        </li>
		                    </ul>
	                    {% endthumbnail %}
		            {% endfor %}
			    {% else %}
	                <table class="table table-bordered">
	                    <tr><th>{% trans 'Title' %}</th><td>{{ file.title }}</td></tr>
	                    <tr><th>{% trans 'Comment '%}</th><td>{{ file.comment }}</td></tr>
	                    <tr><th>{% trans 'Tags' %}</th><td>{{ file.tags|tags }}</td></tr>
	                    <tr><th>{% trans 'Type' %}</th><td>{{ file.mimetype.name }}</td></tr>
	                    <tr><th>{% trans 'File' %}</th><td><a class="btn download" href="{{ MEDIA_URL }}{{ file.file }}">{% trans 'Download' %}</a> <a class="btn copy" href="{{ MEDIA_URL }}{{ file.file }}">{% trans 'Copy link' %}</a>{% if query_string %} <a class="btn" href="#" onclick="OpenFile(ProtectPath('{{ MEDIA_URL }}{{ file.file }}'));return false;">{% trans 'Select' %}</a>{% endif %}</td></tr>
	                    {% if perms.filetags.change_files or perms.filetags.delete_files %}
	                        <tr>
	                            <th>{% trans 'Actions' %}</th>
	                            <td>
	                                {% if perms.filetags.change_files %}<a class="btn btn-primary" href="{% url filetags-edit-file file.id %}{{ query_string }}">{% trans 'Edit' %}</a>{% endif %}
	                                {% if perms.filetags.delete_files %}<a class="btn btn-danger" href="{% url filetags-delete-file file.id %}{{ query_string }}">{% trans 'Delete' %}</a>{% endif %}
	                            </td>
	                        </tr>
	                    {% endif %}
	                </table>
			    {% endif %}
	        </div>
	    {% else %}
            <div class="alert alert-info">
                <h4 class="alert-heading">{% trans 'Error' %}</h4>
                {% trans "File doesn't exists."  %}
            </div>
	    {% endif %}
    </div>
{% endblock %}

filetags/templates/filetags/main.html
{% extends "filetags/base.html" %}
{% load i18n %}
{% load types %}

{% block title %}{% trans 'Search files' %}{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% url django.views.i18n.javascript_catalog %}"></script>
    <script type="text/javascript">
        var MEDIA_URL = '{{ MEDIA_URL }}';
        var QUERY_STRING = '{{ query_string }}'
        var IMAGES_DIR = 'static/images/';
        var THUMB_DIR = 'static/images/thumb/';
        var SEARCH = "{% url filetags-search-files %}";
    </script>
    <script src="{{ STATIC_URL }}filetags/js/csrf.js"></script>
    <script src="{{ STATIC_URL }}filetags/js/bindWithDelay.js"></script>
    <script src="{{ STATIC_URL }}filetags/js/filetags.js"></script>
{% endblock %}

{% block content %}
    <div class="span12">
        <div class="well form-inline">
            <div class="input-append">
	            <input placeholder="{% trans 'Enter tags separated by commas.' %}" type="text" name="tags" class="input-xxlarge" id="appendedInput" />
	            <button class="btn" type="button" id="reset">{% trans 'Clear' %}</button>
	        </div>
	        <select name="type">{% types %}</select>
        </div>
        <ul class="pager well">
            <li class="previous disabled">
                <a href="#">&larr; {% trans 'Previous' %}</a>
            </li>
            <li class="page"></li>
            <li class="next disabled">
                <a href="#">{% trans 'Next' %} &rarr;</a>
            </li>
        </ul>
        <table class="table table-striped well">
            <thead>
                <tr>
                    <th>{% trans 'File' %}</th>
                    <th>{% trans 'Comment' %}</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <ul class="pager well">
            <li class="previous disabled">
                <a href="#">&larr; {% trans 'Previous' %}</a>
            </li>
            <li class="page"></li>
            <li class="next disabled">
                <a href="#">{% trans 'Next' %} &rarr;</a>
            </li>
        </ul>
    </div>
{% endblock %}